name: Hello World

on:
  workflow_dispatch:
  push:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
  print_github_object:
    runs-on: ubuntu-24.04
    steps:
      - name: Print basic GitHub context info
        run: |
          echo "The person who triggered this is: ${{ github.actor }}"
          echo "The repository name is: ${{ github.repository }}"
          echo "The branch or tag name is: ${{ github.ref }}"
          echo "The commit hash is: ${{ github.sha }}"
    
  print_env:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ toJSON(env) }}"

  print_runner:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ toJSON(runner) }}"

