name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
  print_github_object:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ toJSON(github) }}"
    
  print_env:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ toJSON(env) }}"

  print_runner:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ toJSON(runner) }}"

