name: MAC OS TESTING

on: 
    workflow_dispatch:

jobs:
    Hello_WORLD:
        runs-on: macos-latest
        env:
            OS: mac
        steps:
            - name: Helooo
              run: echo "Hello Bhaiyo"
            
            - name: Raam Raam
              run: |
                echo "MY OS Version is ${{env.OS}}"
                echo "Real os is ${{runner.os}}"
                echo "arch is ${{runner.arch}}"
                echo "env is ${{runner.environment}}"
                echo "Temperature is ${{runner.temp}}"


        
