name: Matrix test

on:
    workflow_dispatch:

jobs:
    Matrix:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: true
        timeout-minutes: 5

        steps:
          - name: test
            run: |
              echo "Running on ${{matrix.os}}"

