name: testing

on:
    workflow_dispatch:

jobs:
    First_Job:
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
              os: [ubuntu-latest, ubuntu-24.04]
          max-parallel: 1

      steps:
        - name: First Step
          run: echo "Hello World?"

        - name: Checkout code
          uses: actions/checkout@v6

        - name: Check ls
          run: ls -ltrh

    github-metrics:
        runs-on: ubuntu-latest
        environment: 
        name: production
        permissions:
          contents: write
        steps:
        - uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}

